"""Patch the cloned legged_gym Go2 config for slow, payload-stable STAIR training.

This is a pure text transform: it APPENDS a fenced, auto-generated block to the end of
``legged_gym/envs/go2/go2_parkour_config.py`` that mutates the config classes after they
are defined. Re-running replaces the block (idempotent), so the stock file is never
progressively mangled and the edit is one obvious, reviewable region.

What the block changes (see the approved plan):
  * slower commands  -> cap forward speed below the ~0.5 m/s parkour floor
  * stairs-only terrain curriculum (drop flat / gaps / hurdles / general parkour)
  * carry the O2 payload every episode (added_mass_range centred on the real load)
  * anti-fall        -> stiffen the upright-orientation penalty
  * asset.file       -> the payload-augmented URDF that ``urdf_payload`` writes

Run standalone against a checkout:
    python -m fine_tuning.rl.config_patch --repo /path/to/Extreme-Parkour-Onboard
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

# run-as-script shim so `python -m`/`python config_patch.py` both import the package.
if __package__ in (None, ""):
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from fine_tuning.rl import PATCH_TAG  # noqa: E402
from fine_tuning.rl._payload import PayloadNumbers, load_payload_numbers  # noqa: E402

# Relative path of the Go2 config inside the training repo.
GO2_CONFIG_RELPATH = os.path.join("legged_gym", "envs", "go2", "go2_parkour_config.py")
# URDF the patched config points asset.file at (written by urdf_payload).
O2_URDF_NAME = "go2_o2.urdf"

BEGIN = f"# >>> {PATCH_TAG} (auto-generated by fine_tuning/rl/config_patch.py) >>>"
END = f"# <<< {PATCH_TAG} <<<"


@dataclass(frozen=True)
class StairPatchParams:
    """Tunables for the stair-specialist patch (defaults match the approved plan)."""

    lin_vel_x_max: float = 0.35       # slow walk ceiling (m/s)
    lin_vel_x_min_cmd: float = 0.15   # curriculum lower edge of max_ranges
    orientation_reward: float = -2.0  # stiffer upright penalty (was -1.0)
    urdf_name: str = O2_URDF_NAME


def render_patch_block(payload: PayloadNumbers, params: StairPatchParams = StairPatchParams()) -> str:
    """Return the python block to append to the Go2 config (between the markers)."""
    lo, hi = payload.added_mass_range()
    com = payload.com_m
    return f"""{BEGIN}
# Retrain the parkour policy as a SLOW, payload-stable STAIR climber.
# Regenerate (idempotent) with:
#   python -m fine_tuning.rl.config_patch --repo <repo-dir>
# NOTE: some nested config classes (commands/terrain/domain_rand) are inherited from
# LeggedRobotCfg; mutating them is intended for this single-purpose training repo.
try:
    Go2ParkourCfg  # noqa: F821
except NameError:  # pragma: no cover
    raise SystemExit("O2 stair patch must be appended AFTER class Go2ParkourCfg.")

# --- slower commands: cap forward speed below the ~0.5 m/s parkour over-run floor ---
Go2ParkourCfg.commands.ranges.lin_vel_x = [0.0, {params.lin_vel_x_max}]
Go2ParkourCfg.commands.max_ranges.lin_vel_x = [{params.lin_vel_x_min_cmd}, {params.lin_vel_x_max}]

# --- stairs-only terrain curriculum (ascent), everything else zeroed ---
Go2ParkourCfg.terrain.terrain_dict = {{
    "smooth slope": 0.0, "rough slope up": 0.0, "rough slope down": 0.0,
    "rough stairs up": 0.4, "rough stairs down": 0.0, "discrete": 0.0,
    "stepping stones": 0.0, "gaps": 0.0, "smooth flat": 0.0, "pit": 0.0,
    "wall": 0.0, "platform": 0.0, "large stairs up": 0.3, "large stairs down": 0.0,
    "parkour": 0.0, "parkour_hurdle": 0.0, "parkour_flat": 0.0,
    "parkour_step": 0.3, "parkour_gap": 0.0, "demo": 0.0,
}}
Go2ParkourCfg.terrain.terrain_proportions = list(Go2ParkourCfg.terrain.terrain_dict.values())

# --- carry the O2 payload every episode (numbers from sim/isaac/o2_payload/spec.py) ---
# payload {payload.mass_kg} kg (~{payload.mass_fraction * 100:.0f}% of the {payload.trunk_mass_kg} kg trunk),
# CoM ({com[0]}, {com[1]}, {com[2]}) m, orientation '{payload.orientation}'.
# The fixed mass+CoM live in the URDF (see urdf_payload.py); this DR band keeps every
# episode loaded with at least the tank, plus headroom for robustness.
Go2ParkourCfg.domain_rand.randomize_base_mass = True
Go2ParkourCfg.domain_rand.added_mass_range = [{lo}, {hi}]
Go2ParkourCfg.domain_rand.randomize_base_com = True

# --- anti-fall: stiffen the upright-orientation penalty ---
Go2ParkourCfg.rewards.scales.orientation = {params.orientation_reward}

# --- point the asset at the payload-augmented URDF (urdf_payload.py writes it) ---
Go2ParkourCfg.asset.file = '{{LEGGED_GYM_ROOT_DIR}}/resources/robots/go2/urdf/{params.urdf_name}'
{END}
"""


def _strip_existing(text: str) -> str:
    """Remove a previously-applied patch block (between markers), if present."""
    pattern = re.compile(
        re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?",
        re.DOTALL,
    )
    return pattern.sub("", text)


def apply_to_text(src: str, block: str) -> str:
    """Return ``src`` with exactly one copy of ``block`` appended (idempotent)."""
    base = _strip_existing(src).rstrip("\n")
    return base + "\n\n\n" + block.rstrip("\n") + "\n"


def is_patched(text: str) -> bool:
    return BEGIN in text and END in text


def apply_to_repo(
    repo_dir: os.PathLike | str,
    params: StairPatchParams = StairPatchParams(),
    payload: Optional[PayloadNumbers] = None,
) -> Path:
    """Apply the stair patch to the Go2 config in ``repo_dir``. Returns the file path."""
    cfg_path = Path(repo_dir) / GO2_CONFIG_RELPATH
    if not cfg_path.exists():
        raise FileNotFoundError(
            f"Go2 config not found at {cfg_path} -- is {repo_dir} a clone of the "
            f"Extreme-Parkour-Onboard repo?"
        )
    pay = payload or load_payload_numbers()
    block = render_patch_block(pay, params)
    src = cfg_path.read_text(encoding="utf-8")
    cfg_path.write_text(apply_to_text(src, block), encoding="utf-8")
    return cfg_path


def main(argv: Optional[list] = None) -> int:
    ap = argparse.ArgumentParser(description="Patch the Go2 config for stair training.")
    ap.add_argument("--repo", required=True, help="Path to the cloned training repo.")
    ap.add_argument("--lin-vel-x-max", type=float, default=StairPatchParams.lin_vel_x_max)
    ap.add_argument("--orientation-reward", type=float, default=StairPatchParams.orientation_reward)
    ap.add_argument("--print", action="store_true", help="Print the block; do not write.")
    args = ap.parse_args(argv)
    params = StairPatchParams(
        lin_vel_x_max=args.lin_vel_x_max,
        orientation_reward=args.orientation_reward,
    )
    if args.print:
        print(render_patch_block(load_payload_numbers(), params))
        return 0
    path = apply_to_repo(args.repo, params)
    print(f"[config_patch] patched {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
