"""Write a payload-augmented Go2 URDF (``go2_o2.urdf``) for RL training.

Adds a single fixed link to the stock ``go2.urdf`` that represents the whole on-robot
O2 payload (tank + cradle): its mass, box inertia, and centre-of-mass offset come from
``sim/isaac/o2_payload/spec.py`` -- the same numbers the Isaac runtime mounts. Training
on this URDF means the policy learns to balance the real load (elevated, rearward CoM)
rather than an unloaded robot.

The transform is pure + idempotent: re-running drops any prior ``o2_payload`` link/joint
and re-adds them, so regenerating never stacks duplicates. The stock ``go2.urdf`` is left
untouched; we write a sibling ``go2_o2.urdf`` that ``config_patch`` points ``asset.file`` at.

Run standalone against a checkout:
    python -m fine_tuning.rl.urdf_payload --repo /path/to/Extreme-Parkour-Onboard
"""

from __future__ import annotations

import argparse
import os
import sys
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Optional

if __package__ in (None, ""):
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from fine_tuning.rl._payload import PayloadNumbers, load_payload_numbers  # noqa: E402

GO2_URDF_RELDIR = os.path.join("resources", "robots", "go2", "urdf")
STOCK_URDF_NAME = "go2.urdf"
O2_URDF_NAME = "go2_o2.urdf"

PAYLOAD_LINK = "o2_payload"
PAYLOAD_JOINT = "o2_payload_joint"
# Candidate trunk/base link names, in priority order, if --parent-link isn't given.
_TRUNK_CANDIDATES = ("base", "trunk", "base_link")


def _fmt(x: float) -> str:
    return repr(round(float(x), 8))


def pick_parent_link(root: ET.Element, preferred: Optional[str] = None) -> str:
    """Return the trunk/base link name to bolt the payload to."""
    names = [ln.get("name") for ln in root.findall("link") if ln.get("name")]
    if preferred:
        if preferred in names:
            return preferred
        raise ValueError(f"--parent-link {preferred!r} not in URDF links {names}")
    for cand in _TRUNK_CANDIDATES:
        if cand in names:
            return cand
    if names:
        return names[0]
    raise ValueError("URDF has no <link> elements to attach the payload to.")


def build_payload_link(payload: PayloadNumbers) -> ET.Element:
    """A rigid link carrying the payload mass + box inertia (CoM at the link origin)."""
    ix, iy, iz = payload.inertia_diag
    link = ET.Element("link", {"name": PAYLOAD_LINK})
    inertial = ET.SubElement(link, "inertial")
    ET.SubElement(inertial, "origin", {"xyz": "0 0 0", "rpy": "0 0 0"})
    ET.SubElement(inertial, "mass", {"value": _fmt(payload.mass_kg)})
    ET.SubElement(inertial, "inertia", {
        "ixx": _fmt(ix), "ixy": "0", "ixz": "0",
        "iyy": _fmt(iy), "iyz": "0", "izz": _fmt(iz),
    })
    return link


def build_payload_joint(payload: PayloadNumbers, parent_link: str) -> ET.Element:
    """Fixed joint placing the payload link at the payload CoM in the trunk frame."""
    cx, cy, cz = payload.com_m
    joint = ET.Element("joint", {"name": PAYLOAD_JOINT, "type": "fixed"})
    ET.SubElement(joint, "origin", {"xyz": f"{_fmt(cx)} {_fmt(cy)} {_fmt(cz)}", "rpy": "0 0 0"})
    ET.SubElement(joint, "parent", {"link": parent_link})
    ET.SubElement(joint, "child", {"link": PAYLOAD_LINK})
    return joint


def inject_into_urdf(src_xml: str, payload: PayloadNumbers, parent_link: Optional[str] = None) -> str:
    """Return ``src_xml`` with the payload link+joint added (idempotent)."""
    root = ET.fromstring(src_xml)
    if root.tag != "robot":
        raise ValueError(f"expected <robot> root, got <{root.tag}>")
    # Drop any prior payload elements so regeneration doesn't duplicate.
    for tag, name in (("link", PAYLOAD_LINK), ("joint", PAYLOAD_JOINT)):
        for el in root.findall(tag):
            if el.get("name") == name:
                root.remove(el)
    parent = pick_parent_link(root, parent_link)
    root.append(build_payload_link(payload))
    root.append(build_payload_joint(payload, parent))
    body = ET.tostring(root, encoding="unicode")
    # NB: XML comments may not contain '--', so keep this punctuation simple.
    header = (
        f"<!-- {O2_URDF_NAME}: go2 + O2 payload ({payload.mass_kg} kg @ "
        f"{payload.com_m} m, parent '{parent}'). Auto-generated by "
        f"fine_tuning/rl/urdf_payload.py (regenerate; do not edit). -->\n"
    )
    return header + body + "\n"


def write_o2_urdf(repo_dir: os.PathLike | str, payload: Optional[PayloadNumbers] = None,
                  parent_link: Optional[str] = None) -> Path:
    """Read ``resources/.../go2.urdf`` and write the sibling ``go2_o2.urdf``."""
    urdf_dir = Path(repo_dir) / GO2_URDF_RELDIR
    stock = urdf_dir / STOCK_URDF_NAME
    if not stock.exists():
        raise FileNotFoundError(
            f"Stock URDF not found at {stock}. The training repo does not ship the Go2 "
            f"description (resources/ is gitignored) -- place go2.urdf + meshes there "
            f"first (see fine_tuning/rl/README.md)."
        )
    pay = payload or load_payload_numbers()
    out = urdf_dir / O2_URDF_NAME
    out.write_text(inject_into_urdf(stock.read_text(encoding="utf-8"), pay, parent_link), encoding="utf-8")
    return out


def main(argv: Optional[list] = None) -> int:
    ap = argparse.ArgumentParser(description="Write the payload-augmented Go2 URDF.")
    ap.add_argument("--repo", required=True, help="Path to the cloned training repo.")
    ap.add_argument("--parent-link", default=None, help="Trunk link name (default: auto-detect).")
    args = ap.parse_args(argv)
    out = write_o2_urdf(args.repo, parent_link=args.parent_link)
    pay = load_payload_numbers()
    print(f"[urdf_payload] wrote {out}  (mass={pay.mass_kg} kg, com={pay.com_m} m, "
          f"inertia={pay.inertia_diag})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
