"""isaac_env.py extraction (Phase 2 split): world_setup. Verbatim bodies; only env_state requalification added."""
import logging
try:
    import omni.isaac.core.utils.nucleus as nucleus_utils
    from omni.isaac.core import World
    from omni.isaac.core.articulations import Articulation
    from omni.isaac.core.objects import DynamicCapsule, GroundPlane
    from omni.isaac.core.utils.prims import is_prim_path_valid
    from omni.isaac.core.utils.stage import add_reference_to_stage
    from omni.isaac.core.utils.types import ArticulationAction
    from omni.isaac.core.prims import GeometryPrim
except ModuleNotFoundError:
    import isaacsim.storage.native as nucleus_utils
    from isaacsim.core.api import World
    from isaacsim.core.prims import SingleArticulation as Articulation, SingleGeometryPrim as GeometryPrim
    from isaacsim.core.api.objects import DynamicCapsule, GroundPlane
    from isaacsim.core.utils.prims import is_prim_path_valid
    from isaacsim.core.utils.stage import add_reference_to_stage
    from isaacsim.core.utils.types import ArticulationAction
from sim_logging_utils import log_event

from env import env_state

# Official Isaac Sim 6.0 Go2 asset on Nucleus CDN (mesh-based, preferred)
NUCLEUS_GO2    = "/Isaac/Robots/Unitree/Go2/go2.usd"
# Local fallback candidates (URDF-imported, primitive-shape geometry)
LOCAL_GO2_CANDIDATES = (
    env_state.REPO_ROOT / "sim" / "isaac" / "assets" / "go2.usd" / "go2" / "go2.usda",
    env_state.REPO_ROOT / "sim" / "isaac" / "assets" / "go2_1_files" / "go2.usda",
    env_state.REPO_ROOT / "sim" / "isaac" / "assets" / "go2" / "go2.usda",
)

def build_world(physics_hz: int) -> World:
    world = World(
        stage_units_in_meters=1.0,
        physics_dt=1.0 / physics_hz,
        rendering_dt=1.0 / physics_hz,
    )
    world.scene.add_default_ground_plane()
    return world

class Go2SceneHandle:
    """Minimal robot handle for USDs that render but do not expose a PhysX articulation."""

    def __init__(self, prim) -> None:
        self.prim = prim
        self.name = "go2"
        self.dof_names = []
        self.joint_names = []
        self.num_dof = 0

def _resolve_go2_usd() -> str:
    """Return the best available USD path for Go2.

    Priority order:
    1. Official Nucleus CDN asset (mesh-based, proper 3D geometry)
    2. Local URDF-imported fallback (primitive-shape geometry)
    """
    # --- Try Nucleus first (official Isaac Sim mesh-based asset) ---
    nucleus_server = nucleus_utils.get_assets_root_path()
    if nucleus_server:
        candidate = nucleus_server + NUCLEUS_GO2
        try:
            if nucleus_utils.is_file(candidate):
                log_event(
                    env_state.LOGGER,
                    logging.INFO,
                    "go2_asset_selected",
                    "Using official Isaac Sim Go2 Nucleus asset (mesh geometry)",
                    asset_path=candidate,
                )
                return candidate
        except Exception:
            pass

    # --- Fall back to local URDF-imported asset ---
    for local in LOCAL_GO2_CANDIDATES:
        if local.exists():
            resolved = str(local.resolve())
            import sys
            sys.stderr.write("\n" + "="*80 + "\n")
            sys.stderr.write("WARNING: Nucleus server or official Go2 asset unavailable.\n")
            sys.stderr.write("FALLING BACK TO LOCAL URDF-IMPORTED GO2 ASSET (primitive geometry).\n")
            sys.stderr.write("="*80 + "\n\n")
            sys.stderr.flush()
            log_event(
                env_state.LOGGER,
                logging.WARNING,
                "go2_asset_fallback",
                "Nucleus unavailable; using local URDF-imported Go2 asset (primitive geometry)",
                asset_path=resolved,
            )
            return resolved

    raise FileNotFoundError(
        "Go2 USD not found in Isaac assets or local sim/isaac/assets.\n"
        "Run with Isaac Python: C:\\isaac_sim_600\\python.bat sim\\isaac\\go2_usd_setup.py"
    )

def resolve_go2_body_prim_path(stage) -> str:
    """Return the Go2 prim that follows root motion in this Isaac asset."""
    search_paths = [env_state.GO2_USD_PATH]

    # Include the nested child paths generated by the 6.0 URDF Importer
    go2_prim = stage.GetPrimAtPath(env_state.GO2_USD_PATH)
    if go2_prim and go2_prim.IsValid():
        for child in go2_prim.GetChildren():
            search_paths.append(str(child.GetPath()))

    for root_path in search_paths:
        for child_name in (env_state.BASE_LINK_NAME, "base", "trunk", "base_link"):
            candidate = f"{root_path}/{child_name}"
            try:
                prim = stage.GetPrimAtPath(candidate)
                if prim and prim.IsValid():
                    return candidate
            except Exception:
                pass

    return env_state.GO2_USD_PATH
