"""Patch a cloned robot_lab checkout for slow, O2-payload-stable STAIR training.

robot_lab is IsaacLab + rsl_rl: configs are ``@configclass`` dataclasses whose nested
values are set in ``__post_init__``. The idiomatic, non-destructive way to specialise a
task is therefore to **subclass** the Go2 rough env cfg and override ``__post_init__`` --
appending attribute mutations to the stock file would be silently overwritten when the
parent's ``__post_init__`` runs at instantiation. So this patcher:

  1) WRITES a generated module ``o2_stairs_env_cfg.py`` next to the Go2 config that
     subclasses ``UnitreeGo2RoughEnvCfg`` and, in ``__post_init__``, narrows it to:
       * ascending-stairs-ONLY terrain (drop slopes / boxes / rough / inverted stairs)
       * a SLOW forward command (no strafing, gentle yaw) for a controlled ascent
       * the O2 payload carried every episode (base-mass event centred on the tank)
       * a stiffened upright (flat-orientation) penalty so it does not nose-dive
       * the DEPLOYED PD gains (robot_lab ships kp=25; the sim deploys kp=20)
     while LEAVING the 45-D proprio contract intact (base_lin_vel + height_scan stay
     disabled; obs order/scales, action scales, default pose are inherited unchanged).
  2) INSERTS one idempotent, fenced ``gym.register(...)`` block into the Go2 config
     package ``__init__.py`` so the new task id is importable.

Both edits are idempotent: the module is overwritten and the register block is replaced
between its markers, so regenerating never stacks duplicates and the only hand-editable
files in the repo stay untouched.

Run standalone against a checkout:
    python -m fine_tuning.rl.config_patch --repo /path/to/robot_lab
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Optional, Tuple

# run-as-script shim so `python -m`/`python config_patch.py` both import the package.
if __package__ in (None, ""):
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from fine_tuning.rl import PATCH_TAG, STAIR_TASK_ID  # noqa: E402
from fine_tuning.rl.payload_spec import PayloadNumbers, load_payload_numbers  # noqa: E402

# Go2 velocity-task config package inside the robot_lab checkout. NOTE the
# ``manager_based`` segment -- the path is real and verified against the repo.
GO2_CONFIG_PKG_RELPATH = os.path.join(
    "source", "robot_lab", "robot_lab", "tasks", "manager_based",
    "locomotion", "velocity", "config", "quadruped", "unitree_go2",
)
# Generated env-cfg module + the cfg class it defines.
STAIRS_CFG_MODULE = "o2_stairs_env_cfg"
STAIRS_CFG_CLASS = "UnitreeGo2O2StairsEnvCfg"
# Package __init__ that holds the gym.register(...) calls.
PKG_INIT = "__init__.py"
# rsl_rl runner cfg reused for the new task (lives in agents/rsl_rl_ppo_cfg.py).
RUNNER_CLASS = "UnitreeGo2RoughPPORunnerCfg"

BEGIN = f"# >>> {PATCH_TAG} (auto-generated by fine_tuning/rl/config_patch.py) >>>"
END = f"# <<< {PATCH_TAG} <<<"


@dataclass(frozen=True)
class StairPatchParams:
    """Tunables for the stair-specialist patch (defaults match the approved plan)."""

    lin_vel_x_max: float = 0.5            # slow forward walk ceiling (m/s); command-sampled 0..max
    ang_vel_z_max: float = 0.3            # gentle yaw to track the patient up the stairs (rad/s)
    step_height_min: float = 0.05         # curriculum easy edge of the riser height (m)
    step_height_max: float = 0.18         # curriculum hard edge (commercial riser ~0.15 is in-band)
    orientation_reward: float = -2.5      # flat_orientation_l2 weight (default 0 == OFF -> anti-fall)
    kp: float = 20.0                      # deployed stiffness (rl_locomotion_policy); robot_lab ships 25
    kd: float = 0.5                       # deployed damping (matches robot_lab default, set for clarity)


def render_stairs_cfg_module(
    payload: PayloadNumbers, params: StairPatchParams = StairPatchParams()
) -> str:
    """Return the full text of the generated ``o2_stairs_env_cfg.py`` module."""
    lo, hi = payload.added_mass_range()
    com = payload.com_m
    return f'''# Auto-generated by fine_tuning/rl/config_patch.py ({PATCH_TAG}) -- DO NOT EDIT BY HAND.
# Regenerate (idempotent) with:
#   python -m fine_tuning.rl.config_patch --repo <robot_lab-dir>
#
# Retrains the Unitree Go2 velocity policy into a SLOW, O2-payload-stable STAIR climber
# while preserving the deployed 45-D proprio contract (base_lin_vel + height_scan stay
# disabled by the parent; obs order/scales, action scales, default pose are inherited).
from __future__ import annotations

import isaaclab.terrains as terrain_gen
from isaaclab.utils import configclass

from .rough_env_cfg import UnitreeGo2RoughEnvCfg


@configclass
class {STAIRS_CFG_CLASS}(UnitreeGo2RoughEnvCfg):
    """Go2 rough cfg narrowed to ascending stairs + slow + O2 payload + anti-fall."""

    def __post_init__(self):
        # Inherit the full Go2 rough setup first (45-D obs, action scales, default
        # pose, the base/others mass + CoM events, all reward weights), then narrow.
        super().__post_init__()

        # --- ascending-stairs-ONLY terrain ------------------------------------
        # Replace the slope/box/rough/inverted mix with a single upward pyramid-stairs
        # sub-terrain. With the terrain curriculum on, step_height interpolates from
        # the easy edge to the hard edge across the generator rows.
        gen = self.scene.terrain.terrain_generator
        gen.sub_terrains = {{
            "pyramid_stairs": terrain_gen.MeshPyramidStairsTerrainCfg(
                proportion=1.0,
                step_height_range=({params.step_height_min}, {params.step_height_max}),
                step_width=0.30,
                platform_width=3.0,
                border_width=1.0,
                holes=False,
            ),
        }}

        # --- slow forward walk; no strafing, gentle yaw -----------------------
        self.commands.base_velocity.ranges.lin_vel_x = (0.0, {params.lin_vel_x_max})
        self.commands.base_velocity.ranges.lin_vel_y = (0.0, 0.0)
        self.commands.base_velocity.ranges.ang_vel_z = (-{params.ang_vel_z_max}, {params.ang_vel_z_max})

        # --- carry the O2 payload every episode -------------------------------
        # payload {payload.mass_kg} kg (~{payload.mass_fraction * 100:.0f}% of the {payload.trunk_mass_kg} kg trunk),
        # CoM ({com[0]}, {com[1]}, {com[2]}) m. Numbers from sim/isaac/o2_payload/spec.py.
        # The base-mass startup event ADDS a uniform sample in this band to the trunk,
        # so every episode trains carrying at least the tank (plus robustness headroom).
        self.events.randomize_rigid_body_mass_base.params["mass_distribution_params"] = ({lo}, {hi})

        # --- anti-fall: turn ON + stiffen the upright (flat-orientation) penalty
        # It is 0.0 (pruned) in the stock Go2 cfg; a negative weight punishes tipping.
        self.rewards.flat_orientation_l2.weight = {params.orientation_reward}

        # --- match the DEPLOYED PD gains (rl_locomotion_policy kp={params.kp}, kd={params.kd}) ---
        # robot_lab ships stiffness=25.0; the sim deploys kp=20.0, so align here to keep
        # the retrained policy consistent with the gains it runs under in Isaac.
        self.scene.robot.actuators["legs"].stiffness = {params.kp}
        self.scene.robot.actuators["legs"].damping = {params.kd}

        # The parent prunes zero-weight rewards ONLY when the class name matches its
        # own (UnitreeGo2RoughEnvCfg/...FlatEnvCfg); our subclass name does not, so the
        # guard is False and we must prune explicitly -- this keeps flat_orientation_l2
        # (now non-zero) while dropping the terms that are still zero.
        self.disable_zero_weight_rewards()
'''


def render_register_block() -> str:
    """Return the idempotent gym.register block to append to the package __init__."""
    return f"""{BEGIN}
# Registers the slow, O2-payload, ascending-stairs Go2 retrain task. Regenerate
# (idempotent) with: python -m fine_tuning.rl.config_patch --repo <robot_lab-dir>
import gymnasium as gym  # noqa: E402  (re-import is harmless; gym is already imported above)

from . import agents  # noqa: E402

gym.register(
    id="{STAIR_TASK_ID}",
    entry_point="isaaclab.envs:ManagerBasedRLEnv",
    disable_env_checker=True,
    kwargs={{
        "env_cfg_entry_point": f"{{__name__}}.{STAIRS_CFG_MODULE}:{STAIRS_CFG_CLASS}",
        "rsl_rl_cfg_entry_point": f"{{agents.__name__}}.rsl_rl_ppo_cfg:{RUNNER_CLASS}",
    }},
)
{END}
"""


def _strip_existing(text: str) -> str:
    """Remove a previously-applied fenced block (between markers), if present."""
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", re.DOTALL)
    return pattern.sub("", text)


def apply_to_init_text(src: str, block: str) -> str:
    """Return ``src`` with exactly one copy of the register ``block`` appended."""
    base = _strip_existing(src).rstrip("\n")
    return base + "\n\n\n" + block.rstrip("\n") + "\n"


def is_patched(init_text: str) -> bool:
    return BEGIN in init_text and END in init_text


def go2_config_pkg(repo_dir: os.PathLike | str) -> Path:
    return Path(repo_dir) / GO2_CONFIG_PKG_RELPATH


def apply_to_repo(
    repo_dir: os.PathLike | str,
    params: StairPatchParams = StairPatchParams(),
    payload: Optional[PayloadNumbers] = None,
) -> Tuple[Path, Path]:
    """Apply the stair patch to a robot_lab checkout.

    Writes ``o2_stairs_env_cfg.py`` and inserts the register block into the package
    ``__init__.py``. Returns (cfg_module_path, init_path).
    """
    pkg = go2_config_pkg(repo_dir)
    init_path = pkg / PKG_INIT
    rough = pkg / "rough_env_cfg.py"
    if not init_path.exists() or not rough.exists():
        raise FileNotFoundError(
            f"Go2 config package not found/complete at {pkg} (missing {PKG_INIT} or "
            f"rough_env_cfg.py) -- is {repo_dir} a clone of fan-ziqi/robot_lab?"
        )
    pay = payload or load_payload_numbers()

    cfg_path = pkg / f"{STAIRS_CFG_MODULE}.py"
    cfg_path.write_text(render_stairs_cfg_module(pay, params), encoding="utf-8")

    src = init_path.read_text(encoding="utf-8")
    init_path.write_text(apply_to_init_text(src, render_register_block()), encoding="utf-8")
    return cfg_path, init_path


def main(argv: Optional[list] = None) -> int:
    ap = argparse.ArgumentParser(description="Patch robot_lab for O2 stair training.")
    ap.add_argument("--repo", required=True, help="Path to the cloned robot_lab checkout.")
    ap.add_argument("--lin-vel-x-max", type=float, default=StairPatchParams.lin_vel_x_max)
    ap.add_argument("--step-height-max", type=float, default=StairPatchParams.step_height_max)
    ap.add_argument("--orientation-reward", type=float, default=StairPatchParams.orientation_reward)
    ap.add_argument("--print", action="store_true", help="Print the generated module; do not write.")
    args = ap.parse_args(argv)
    params = StairPatchParams(
        lin_vel_x_max=args.lin_vel_x_max,
        step_height_max=args.step_height_max,
        orientation_reward=args.orientation_reward,
    )
    if args.print:
        print(render_stairs_cfg_module(load_payload_numbers(), params))
        print("\n# --- register block (appended to package __init__.py) ---\n")
        print(render_register_block())
        return 0
    cfg_path, init_path = apply_to_repo(args.repo, params)
    print(f"[config_patch] wrote   {cfg_path}")
    print(f"[config_patch] patched {init_path}  (registered {STAIR_TASK_ID})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
